In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("listings.csv")

In [4]:
df.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,27262,"AQA-No7, Great mattress, high speed internet",37177,Emmanouil,NaN,ΑΜΠΕΛΟΚΗΠΟΙ,37.98924,23.76500,Entire home/apt,131.0,1,29,2024-11-18,0.19,1,355,5,00002433111
1,33945,Spacious Cosy aprtm very close to Metro!,146553,Katerina,NaN,ΑΓΙΟΣ ΝΙΚΟΛΑΟΣ,38.00673,23.72775,Entire home/apt,47.0,4,78,2024-11-11,0.45,2,361,9,00000874421
2,49489,Ermou 44 - 3bdr apt in the heart of Athens,225612,Stathis,NaN,ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ,37.97670,23.73064,Entire home/apt,200.0,2,140,2024-07-14,0.86,1,354,4,00000876484
3,60394,Cosy apartment! Great central Athens location!,290864,Dimitra,NaN,ΣΤΑΔΙΟ,37.96738,23.74038,Entire home/apt,50.0,6,34,2024-11-02,0.29,1,180,4,01039140005
4,133835,Studio in upscale/central location,656936,Elena,NaN,ΚΟΛΩΝΑΚΙ,37.97794,23.74371,Entire home/apt,55.0,3,27,2024-09-15,0.17,1,357,6,00001227000

In [5]:
df.info

<bound method DataFrame.info of                         id                                              name  \
0                    27262      AQA-No7, Great mattress, high speed internet
1                    33945          Spacious Cosy aprtm very close to Metro!
2                    49489        Ermou 44 - 3bdr apt in the heart of Athens
3                    60394    Cosy apartment! Great central Athens location!
4                   133835                Studio in upscale/central location
...                    ...                                               ...
14637  1318251942056598277       Dreamy Athens Penthouse With Acropolis View
14638  1318276742106864141                            Αθήνα κατάλυμα Rafaela
14639  1318307768558324736  Blueground | Ampelokipoi, AC, w/d, nr Lycabettus
14640  1318405788507138933                                         Cozy Nest
14641  1318601800941001079            Vintage Elegance in Koukaki w/ balcony

         host_id   host_name  neighbourhood_group             neighbourhood  \
0          37177   Emmanouil                  NaN               ΑΜΠΕΛΟΚΗΠΟΙ
1         146553    Katerina                  NaN            ΑΓΙΟΣ ΝΙΚΟΛΑΟΣ
2         225612     Stathis                  NaN    ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ
3         290864     Dimitra                  NaN                    ΣΤΑΔΙΟ
4         656936       Elena                  NaN                  ΚΟΛΩΝΑΚΙ
...          ...         ...                  ...                       ...
14637   25811452         Iro                  NaN    ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ
14638  666320836    Γεώργιος                  NaN         ΑΚΑΔΗΜΙΑ ΠΛΑΤΩΝΟΣ
14639  221534605  Blueground                  NaN               ΑΜΠΕΛΟΚΗΠΟΙ
14640  650411545         Ion                  NaN  ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ
14641   31290848       Nasos                  NaN       ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ

        latitude  longitude        room_type  price  minimum_nights  \
0      37.989240  23.765000  Entire home/apt  131.0               1
1      38.006730  23.727750  Entire home/apt   47.0               4
2      37.976700  23.730640  Entire home/apt  200.0               2
3      37.967380  23.740380  Entire home/apt   50.0               6
4      37.977940  23.743710  Entire home/apt   55.0               3
...          ...        ...              ...    ...             ...
14637  37.979336  23.726354  Entire home/apt  133.0               2
14638  37.992753  23.709720  Entire home/apt   60.0               1
14639  37.983118  23.756604  Entire home/apt   70.0              31
14640  37.984651  23.735136  Entire home/apt   45.0               1
14641  37.968246  23.726156  Entire home/apt   72.0               1

       number_of_reviews last_review  reviews_per_month  \
0                     29  2024-11-18               0.19
1                     78  2024-11-11               0.45
2                    140  2024-07-14               0.86
3                     34  2024-11-02               0.29
4                     27  2024-09-15               0.17
...                  ...         ...                ...
14637                  0         NaN                NaN
14638                  0         NaN                NaN
14639                  0         NaN                NaN
14640                  0         NaN                NaN
14641                  0         NaN                NaN

       calculated_host_listings_count  availability_365  \
0                                   1               355
1                                   2               361
2                                   1               354
3                                   1               180
4                                   1               357
...                               ...               ...
14637                               3               350
14638                               1               365
14639                              23               365
14640                               1               365
14641                              70               364

       number_of_reviews_ltm      license
0                          5  00002433111
1                          9  00000874421
2                          4  00000876484
3                          4  01039140005
4                          6  00001227000
...                      ...          ...
14637                      0  00003108542
14638                      0  00002888548
14639                      0  00002764099
14640                      0  00003072289
14641                      0  00003026761

[14642 rows x 18 columns]>