In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("listings.csv")

In [5]:
df.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,27262,"AQA-No7, Great mattress, high speed internet",37177,Emmanouil,NaN,ΑΜΠΕΛΟΚΗΠΟΙ,37.98924,23.76500,Entire home/apt,131.0,1,29,2024-11-18,0.19,1,355,5,00002433111
1,33945,Spacious Cosy aprtm very close to Metro!,146553,Katerina,NaN,ΑΓΙΟΣ ΝΙΚΟΛΑΟΣ,38.00673,23.72775,Entire home/apt,47.0,4,78,2024-11-11,0.45,2,361,9,00000874421
2,49489,Ermou 44 - 3bdr apt in the heart of Athens,225612,Stathis,NaN,ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ,37.97670,23.73064,Entire home/apt,200.0,2,140,2024-07-14,0.86,1,354,4,00000876484
3,60394,Cosy apartment! Great central Athens location!,290864,Dimitra,NaN,ΣΤΑΔΙΟ,37.96738,23.74038,Entire home/apt,50.0,6,34,2024-11-02,0.29,1,180,4,01039140005
4,133835,Studio in upscale/central location,656936,Elena,NaN,ΚΟΛΩΝΑΚΙ,37.97794,23.74371,Entire home/apt,55.0,3,27,2024-09-15,0.17,1,357,6,00001227000